name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check file contents
      run: ls -al
    - name: Build the Docker image      
      run: docker build . --file Dockerfile --tag remote-dev-cpp:$(date +%s)
